# Generated by Django 5.0 on 2023-12-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, verbose_name='Place description'),
        ),
    ]
