# Generated by Django 5.0 on 2023-12-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='color',
            field=models.CharField(default='green', max_length=50, verbose_name='Place Color'),
        ),
    ]
